config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about', to: 'homes#about', as: 'about'
  
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :edit, :update, :destroy, :show] do
    resource  :favorite,       only: [:create, :destroy]
    resources :book_comments,  only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title,
            presence: true

  validates :body,
            presence: true,
            length: { maximum: 200 }

  def favorited_by?(user)
    return false unless user
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

  validates :name,
            uniqueness: true,
            length: { in: 2..20 }

  validates :introduction,
            length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end


  
  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    # Ensure only the owner can delete their comment
    comment = current_user.book_comments.find_by(id: params[:id], book_id: book.id)
    comment&.destroy
    redirect_to book_path(book)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book,          only: [:show, :edit, :update, :destroy]
  before_action :correct_user!,     only: [:edit, :update, :destroy]

  def index
    @new_book = Book.new
    @books = Book.includes(:user).order(created_at: :desc)
  end

  def show
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit; end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      @books = Book.includes(:user).order(created_at: :desc)
      @new_book = @book
      render :index, status: :unprocessable_entity
    end
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "Book was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private
  def set_book
    @book = Book.includes(:user).find(params[:id])
  end

  def correct_user!
    redirect_to books_path unless current_user && @book.user_id == current_user.id
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_or_initialize_by(book_id: book.id)
    favorite.save
    redirect_back fallback_location: book_path(book)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite&.destroy
    redirect_back fallback_location: book_path(book)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.order(created_at: :desc)   
  end
  
  def show
    @books = @user.books.order(created_at: :desc)
    @book  = Book.new
  end

  def edit; end
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Profile was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def set_user; @user = User.find(params[:id]); end

  def is_matching_login_user
    return if @user == current_user
    redirect_to user_path(current_user)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/views/books/_floating_form.html.erb
<div class="card-body">
  <h2>New book</h2>
  <%= form_with model: book, url: books_path, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.label :body, "Opinion" %>
      <%= f.text_area :body, rows: 3, class: "form-control" %>
    </div>

    <div class="form-group mt-3">
      <%= f.submit "Create Book", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="mx-auto px-5" style="max-width: 500px;">
    <h1>Editing Book</h1>
    <%= form_with model: @book, local: true do |f| %>
      <div class="form-group">
        <%= f.label :title, "Title" %>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>

      <div class="form-group">
        <%= f.label :body, "Opinion" %>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to "Show", @book %> |
    <%= link_to "Back", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info_card", user: current_user %>
      <%= render "books/floating_form", book: @new_book %>
    </div>

    <div class="col-md-8 offset-md-1 pt-3">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th style="width: 20%;"></th>
            <th style="width: 20%;">Title</th>
            <th style="width: 20%;">Opinion</th>
            <th style="width: 20%;"></th>
            <th style="width: 20%;"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <% u = book.user %>
            <tr>
              <td>
                <%= link_to user_path(u) do %>
                  <% if u&.profile_image&.attached? %>
                    <%= image_tag u.profile_image, size: "60x60", alt: u.name %>
                  <% else %>
                    <%= image_tag "no_image.jpg", size: "60x60", alt: "No image" %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td class="text-center align-middle">
                <% if user_signed_in? %>
                  <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorite_path(book), method: :delete, class: "text-danger" do %>
                      <i class="fas fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorite_path(book), method: :post, class: "text-secondary" do %>
                      <i class="far fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  <% end %>
                <% else %>
                  <span class="text-secondary"><i class="far fa-heart"></i> <%= book.favorites.count %></span>
                <% end %>
              </td>
              <td class="text-center align-middle text-muted">
                コメント数: <%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @books if defined?(paginate) %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info_card", user: @book.user %>
      <%= render "books/floating_form", book: @new_book %>
    </div>

  <div class="col-md-8 offset-md-1 pt-3">
    <h2>Book detail</h2>
    <table class="table table-hover table-inverse" style="table-layout: fixed; width: 100%;">
      <thead>
        <tr>
          <th style="width: 20%;"></th>
          <th style="width: 20%;">Title</th>
          <th style="width: 20%;">Opinion</th>
          <th style="width: 20%;"></th>
          <th style="width: 20%;"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <!-- User -->
          <td>
            <%= link_to user_path(@book.user) do %>
              <% if @book.user.profile_image&.attached? %>
                <%= image_tag @book.user.profile_image, size: "60x60", alt: @book.user.name %>
              <% else %>
                <%= image_tag "no_image.jpg", size: "60x60", alt: "No image" %>
              <% end %>
            <% end %>
          </td>

          <!-- Title -->
          <td><%= link_to @book.title, book_path(@book) %></td>

          <!-- Opinion -->
          <td><%= simple_format(@book.body) %></td>

          <!-- Favorite column -->
          <td class="text-center align-middle">
            <% if user_signed_in? %>
              <% if @book.favorited_by?(current_user) %>
                <%= link_to book_favorite_path(@book), method: :delete, class: "text-danger" do %>
                  <i class="fas fa-heart"></i> <%= @book.favorites.count %>
                <% end %>
              <% else %>
                <%= link_to book_favorite_path(@book), method: :post, class: "text-secondary" do %>
                  <i class="far fa-heart"></i> <%= @book.favorites.count %>
                <% end %>
              <% end %>
            <% else %>
              <span class="text-secondary"><i class="far fa-heart"></i> <%= @book.favorites.count %></span>
            <% end %>
          </td>

          <!-- Comments count column -->
          <td class="text-center align-middle text-muted">
            コメント数: <%= @book.book_comments.count %>
          </td>
        </tr>
      </tbody>
    </table>

      <% if @book.user_id == current_user&.id %>
        <div class="mb-3">
          <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-sm btn-success mr-2' %>
          <%= link_to 'Destroy', book_path(@book), method: :delete,
                      data: { confirm: '本当に消しますか？' },
                      class: 'btn btn-sm btn-danger' %>
        </div>
      <% end %>

      <!-- Comments -->
      <div class="card">
        <div class="card-header">
          コメント一覧
        </div>
        <ul class="list-group list-group-flush">
          <% @book.book_comments.includes(:user).order(created_at: :desc).each do |bc| %>
            <li class="list-group-item d-flex align-items-center justify-content-between">
              <div>
                <% if bc.user.profile_image&.attached? %>
                  <%= image_tag bc.user.profile_image, size: "40x40", class: "mr-2 rounded" %>
                <% else %>
                  <%= image_tag "no_image.jpg", size: "40x40", class: "mr-2 rounded" %>
                <% end %>
                <strong><%= link_to bc.user.name, user_path(bc.user) %></strong>
                <small class="text-muted ml-2"><%= bc.created_at.strftime('%Y/%m/%d') %></small>
                <div class="mt-1"><%= bc.comment %></div>
              </div>
              <% if bc.user_id == current_user&.id %>
                <%= link_to "Destroy", book_book_comment_path(@book, bc), method: :delete,
                            data: { confirm: "このコメントを削除しますか？" },
                            class: "btn btn-sm btn-outline-danger" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>

      <% if user_signed_in? %>
        <div class="card mt-3">
          <div class="card-body">
            <%= form_with model: [@book, @book_comment] do |f| %>
              <div class="form-group">
                <%= f.text_area :comment, rows: 4, placeholder: "コメントをここに", class: "form-control" %>
              </div>
              <%= f.submit "送信する", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="col-lg-6 mx-auto text-center">
    <h1>
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
</div>

app/views/homes/top.html.erb
<div class="col-lg-6 mx-auto text-left">
  <h1>
    welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
  </h1>
</div>

<div class="col-lg-6 mx-auto text-left mt-4">
  <p>In <strong>Bookers</strong>,</p>
  <p>you can share and exchange your opinions , impressions , and emotions</p>
  <p>about various books!</p>

  <div class="mt-4 text-center">
    <%= link_to "Log in", new_user_session_path,
          class: "btn btn-info btn-lg w-75 mx-auto d-block mb-3" %>
    <%= link_to "Sign up", new_user_registration_path,
          class: "btn btn-success btn-lg w-75 mx-auto d-block" %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% unless controller_path == 'devise/sessions' %>
  <% targets = [] %>
  <% targets << @book if defined?(@book) && @book && @book.errors.any? %>
  <% targets << @new_book if defined?(@new_book) && @new_book && @new_book.errors.any? %>
  <% targets << @user if defined?(@user) && @user && @user.errors.any? %>
  <% targets << resource if defined?(resource) && resource && resource.respond_to?(:errors) && resource.errors.any? %>
  <% obj = targets.first %>
  <% if obj %>
    <div>
      <h3><%= pluralize(obj.errors.count, 'error') %> prohibited this <%= obj.class.model_name.human.downcase %> from being saved:</h3>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://kit.fontawesome.com/580e10ba65.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-home mr-1"></i> Home'),
                              user_path(current_user), class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-users mr-1"></i> Users'),
                              users_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-book-open mr-1"></i> Books'),
                              books_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-sign-out-alt mr-1"></i> Log out'),
                              destroy_user_session_path, method: :delete, class: "nav-link text-light" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-home mr-1"></i> Home'),
                              root_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-link mr-1"></i> About'),
                              about_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-user-plus mr-1"></i> Sign up'),
                              new_user_registration_path, class: "nav-link text-light" %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fas fa-sign-in-alt mr-1"></i> Log in'),
                              new_user_session_path, class: "nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container mt-3">
      <% if flash[:notice].present? %>
        <div class="flash-message notice"><%= flash[:notice] %></div>
      <% end %>

      <%= render 'layouts/errors' %>
    </div>

    <main class="container-fluid my-3">
      <%= yield %>
    </main>

    <footer>
      <div class="container text-center pb-5">
        CopyRight Infratop.inc
      </div>
    </footer>
  </body>
</html>

app/views/users/_info_card.html.erb
<div class="card-body">
  <h2 class="mb-2">User info</h2>

  <div class="text-left mb-2">
    <% if user.profile_image&.attached? %>
      <%= image_tag user.profile_image, alt: user.name, size: "120x120" %>
    <% else %>
      <%= image_tag "no_image.jpg", alt: "NO IMAGE", size: "120x120" %>
    <% end %>
  </div>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction.to_s %></th>
      </tr>
    </tbody>
  </table>

  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="mx-auto px-5" style="max-width: 500px;">
    <h2>User info</h2>
    <%= form_with model: @user, local: true, html: { multipart: true } do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :profile_image, "Image" %>
        <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
      </div>

      <div class="form-group">
        <%= f.label :introduction, "Introduction" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info_card", user: current_user %>
      <%= render "books/floating_form", book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1 pt-3">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |u| %>
            <tr>
              <td>
                <% if u.profile_image&.attached? %>
                  <%= image_tag u.profile_image, size: "60x60", alt: u.name %>
                <% else %>
                  <%= image_tag "no_image.jpg", size: "60x60", alt: "No image" %>
                <% end %>
              </td>
              <td><%= u.name %></td>
              <td><%= link_to "Show", user_path(u) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @users if defined?(paginate) %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info_card", user: @user %>
      <%= render "books/floating_form", book: Book.new %>
    </div>

    <div class="col-md-8 offset-md-1 pt-3">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th style="width: 20%;"></th>
            <th style="width: 20%;">Title</th>
            <th style="width: 20%;">Opinion</th>
            <th style="width: 20%;"></th>
            <th style="width: 20%;"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if @user.profile_image&.attached? %>
                  <%= link_to user_path(@user) do %>
                    <%= image_tag @user.profile_image, size: "60x60", alt: @user.name %>
                  <% end %>
                <% else %>
                  <%= link_to user_path(@user) do %>
                    <%= image_tag "no_image.jpg", size: "60x60", alt: "No image" %>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td class="text-center align-middle">
                <% if user_signed_in? %>
                  <% if book.favorited_by?(current_user) %>
                    <%= link_to book_favorite_path(book), method: :delete, class: "text-danger" do %>
                      <i class="fas fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  <% else %>
                    <%= link_to book_favorite_path(book), method: :post, class: "text-secondary" do %>
                      <i class="far fa-heart"></i> <%= book.favorites.count %>
                    <% end %>
                  <% end %>
                <% else %>
                  <span class="text-secondary"><i class="far fa-heart"></i> <%= book.favorites.count %></span>
                <% end %>
              </td>
              <td class="text-center align-middle text-muted">
                コメント数: <%= book.book_comments.count %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>